Use atom.workspace.getActiveTextEditor()
Instead of listening to every single text editor, listen globally and
use getActiveTextEditor() to operate on the text editor in question.

75 tests fail with this commit.  The error on all of them is like this:

  TypeError: Cannot read property 'transact' of undefined
  at AtomicEmacs.transposeWords (.../atomic-emacs.coffee:92:11)
  at atomic-emacs-spec.coffee:20:20